// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: delete_chirp_by_id.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteChirpById = `-- name: DeleteChirpById :exec
DELETE FROM Chirps WHERE id = $1
`

func (q *Queries) DeleteChirpById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChirpById, id)
	return err
}
