// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: delete_user.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserById = `-- name: DeleteUserById :exec
DELETE FROM Users WHERE id = $1
`

func (q *Queries) DeleteUserById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserById, id)
	return err
}
