// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: update_user_status.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE Users SET
updated_at =  NOW(),
is_chirpy_red = $2
WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID          uuid.UUID
	IsChirpyRed bool
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus, arg.ID, arg.IsChirpyRed)
	return err
}
